@baseUrl = http://localhost:5000

### Health Check
GET {{baseUrl}}/api/health
Accept: application/json

###

### Get All Stations
GET {{baseUrl}}/api/v1/stations
Accept: application/json

###

### Get Battery Models
GET {{baseUrl}}/api/batterymodels
Accept: application/json

###

### Get Inventory Health
GET {{baseUrl}}/api/inventory/health
Accept: application/json

###
