name: Build .NET API

on:
  push:
    branches: [ main, minh ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore EVBSS.sln
    
    - name: Build solution
      run: dotnet build EVBSS.sln --no-restore --configuration Release
    
    - name: Check for compilation warnings
      run: dotnet build EVBSS.sln --no-restore --configuration Release --verbosity normal
    
    # Skip tests for now since no test project exists
    # - name: Run tests
    #   run: dotnet test EVBSS.sln --no-build --configuration Release --verbosity normal