# This workflow will build, test, and deploy a .NET Web API application

name: .NET Web API Build and Test

on:
  push:
    branches: [ "main", "khai" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: EVBSS.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --no-restore --configuration Release

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --no-build --configuration Release --verbosity normal
